name: Build, Test and Dockerize

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build app
        run: |
          cd hello-world-app 
          npm install
          npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run unit tests
        run: |
          cd hello-world-app
          npm install
          npm run test:unit

  build-container:
    needs: test
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4
      - name: Build image and push it to the registry
        id: build-image
        env:
          CONTAINER_REGISTRY: ghcr.io/fourco-ffgm
          CONTAINER_REPOSITORY: fourco-cicd
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd hello-world-app
          docker build -t $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$IMAGE_TAG . --file Dockerfile
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$IMAGE_TAG